project:
  type: book

book:
  title: "학습분석학 방법론과 지침서"
  subtitle: "R을 활용한 실전 가이드"
  navbar:
    left:
      - text: "홈"
        href: index.qmd
      - text: "학습분석학 방법론과 지침서"
        href: index.qmd
      - text: "고급 학습분석학 방법론"
        href: "https://swyoon31.github.io/alabook-kr/"
    right:
      - icon: github
        href: https://github.com/swyoon31/labook-kr
        aria-label: GitHub 저장소
  chapters:
    - index.qmd
    - part: "시작하기"
      chapters:
        - chapters/개관.qmd
        - chapters/데이터.qmd
    - part: "머신러닝"
      chapters:
        - chapters/예측 모델링.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
  epub:
    cover-image: cover.png   # EPUB을 만들 때만 표지로 사용됨